Update OWASP-dependency-check.yml

diff --git a/.github/workflows/OWASP-dependency-check.yml b/.github/workflows/OWASP-dependency-check.yml
--- a/.github/workflows/OWASP-dependency-check.yml
+++ b/.github/workflows/OWASP-dependency-check.yml
@@ -26,8 +26,12 @@ jobs:
         run: |
           wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
           unzip dependency-check-8.1.2-release.zip -d dependency-check
-          chmod +x dependency-check/bin/dependency-check.sh
-
+          if [ -f dependency-check/dependency-check/bin/dependency-check.sh ]; then
+            chmod +x dependency-check/dependency-check/bin/dependency-check.sh
+          else
+            echo "Dependency Check installation failed: dependency-check.sh not found."
+            exit 1
+          fi
       - name: Run OWASP Dependency Check
         run: |
           dependency-check/bin/dependency-check.sh --project "Express.js Application" --scan . --format "ALL" --out dependency-check-report
